import { Word } from './types';

export const TOTAL_QUESTIONS = 10;

// Helper to generate word objects easily
const w = (eng: string, kor: string, level: number): Word => ({ eng, kor, level });

// Database of 400+ words spread across 5 levels
export const WORD_DATABASE: Word[] = [
  // --- LEVEL 1 (Very Easy / Basic) ---
  w('Apple', '사과', 1), w('Banana', '바나나', 1), w('Cat', '고양이', 1), w('Dog', '강아지', 1),
  w('Egg', '달걀', 1), w('Fish', '물고기', 1), w('Good', '좋은', 1), w('Hat', '모자', 1),
  w('Ice', '얼음', 1), w('Jam', '잼', 1), w('Key', '열쇠', 1), w('Lion', '사자', 1),
  w('Mom', '엄마', 1), w('Dad', '아빠', 1), w('No', '아니오', 1), w('Yes', '네', 1),
  w('Pen', '펜', 1), w('Queen', '여왕', 1), w('Red', '빨간색', 1), w('Sun', '해', 1),
  w('Tree', '나무', 1), w('Up', '위', 1), w('Van', '승합차', 1), w('Water', '물', 1),
  w('Box', '상자', 1), w('Yellow', '노란색', 1), w('Zoo', '동물원', 1), w('Ant', '개미', 1),
  w('Bag', '가방', 1), w('Cap', '모자(캡)', 1), w('Desk', '책상', 1), w('Eye', '눈', 1),
  w('Fox', '여우', 1), w('Gum', '껌', 1), w('Hand', '손', 1), w('Ink', '잉크', 1),
  w('Jet', '제트기', 1), w('King', '왕', 1), w('Leg', '다리', 1), w('Man', '남자', 1),
  w('Net', '그물', 1), w('Owl', '부엉이', 1), w('Pig', '돼지', 1), w('Run', '달리다', 1),
  w('Six', '육(6)', 1), w('Ten', '십(10)', 1), w('Bus', '버스', 1), w('Car', '자동차', 1),
  w('One', '일(1)', 1), w('Two', '이(2)', 1), w('Three', '삼(3)', 1), w('Four', '사(4)', 1),
  w('Five', '오(5)', 1), w('Blue', '파란색', 1), w('Bed', '침대', 1), w('Cup', '컵', 1),
  w('Doll', '인형', 1), w('Fan', '선풍기', 1), w('Gun', '총', 1), w('Hen', '암탉', 1),
  w('Map', '지도', 1), w('Nut', '견과류', 1), w('Pan', '프라이팬', 1), w('Rat', '쥐', 1),
  w('Sky', '하늘', 1), w('Top', '팽이', 1), w('Bat', '박쥐', 1), w('Cow', '소', 1),
  w('Ear', '귀', 1), w('Fly', '파리', 1), w('Gas', '가스', 1), w('Hot', '뜨거운', 1),
  w('Jar', '병', 1), w('Lip', '입술', 1), w('Mud', '진흙', 1), w('Oil', '기름', 1),
  w('Pin', '핀', 1), w('Sad', '슬픈', 1), w('Toy', '장난감', 1), w('Wet', '젖은', 1),

  // --- LEVEL 2 (Easy / Common Objects & Actions) ---
  w('Ball', '공', 2), w('Bear', '곰', 2), w('Bird', '새', 2), w('Book', '책', 2),
  w('Cake', '케이크', 2), w('Door', '문', 2), w('Duck', '오리', 2), w('Face', '얼굴', 2),
  w('Farm', '농장', 2), w('Foot', '발', 2), w('Girl', '소녀', 2), w('Gold', '금', 2),
  w('Hair', '머리카락', 2), w('Home', '집', 2), w('Jump', '점프하다', 2), w('Kite', '연', 2),
  w('Lake', '호수', 2), w('Lamp', '램프', 2), w('Love', '사랑', 2), w('Milk', '우유', 2),
  w('Moon', '달', 2), w('Name', '이름', 2), w('Nose', '코', 2), w('Park', '공원', 2),
  w('Rain', '비', 2), w('Ring', '반지', 2), w('Rose', '장미', 2), w('Ship', '배', 2),
  w('Shoe', '신발', 2), w('Sock', '양말', 2), w('Star', '별', 2), w('Swim', '수영하다', 2),
  w('Time', '시간', 2), w('Walk', '걷다', 2), w('Wind', '바람', 2), w('Work', '일하다', 2),
  w('Year', '년(해)', 2), w('Baby', '아기', 2), w('Boat', '보트', 2), w('Body', '몸', 2),
  w('City', '도시', 2), w('Coin', '동전', 2), w('Corn', '옥수수', 2), w('Drum', '북', 2),
  w('Fire', '불', 2), w('Flag', '깃발', 2), w('Frog', '개구리', 2), w('Gate', '대문', 2),
  w('Gift', '선물', 2), w('Goat', '염소', 2), w('Hand', '손', 2), w('Head', '머리', 2),
  w('Hill', '언덕', 2), w('Iron', '다리미', 2), w('Jeep', '지프차', 2), w('Leaf', '나뭇잎', 2),
  w('Left', '왼쪽', 2), w('Lime', '라임', 2), w('Line', '선', 2), w('Lock', '자물쇠', 2),
  w('Meat', '고기', 2), w('Neck', '목', 2), w('News', '뉴스', 2), w('Nine', '구(9)', 2),
  w('Open', '열다', 2), w('Page', '페이지', 2), w('Pipe', '파이프', 2), w('Play', '놀다', 2),
  w('Pool', '수영장', 2), w('Read', '읽다', 2), w('Rice', '쌀/밥', 2), w('Road', '길', 2),
  w('Roof', '지붕', 2), w('Room', '방', 2), w('Salt', '소금', 2), w('Sand', '모래', 2),
  w('Seat', '좌석', 2), w('Sing', '노래하다', 2), w('Snow', '눈(날씨)', 2), w('Soap', '비누', 2),

  // --- LEVEL 3 (Medium / Places, Feelings, Colors) ---
  w('Black', '검은색', 3), w('Bread', '빵', 3), w('Brown', '갈색', 3), w('Brush', '붓/빗', 3),
  w('Candy', '사탕', 3), w('Chair', '의자', 3), w('Child', '아이', 3), w('Clean', '깨끗한', 3),
  w('Clock', '시계', 3), w('Cloud', '구름', 3), w('Color', '색깔', 3), w('Dance', '춤추다', 3),
  w('Dress', '드레스', 3), w('Drink', '마시다', 3), w('Drive', '운전하다', 3), w('Earth', '지구', 3),
  w('Eight', '팔(8)', 3), w('Fruit', '과일', 3), w('Glass', '유리/잔', 3), w('Grape', '포도', 3),
  w('Grass', '풀/잔디', 3), w('Green', '초록색', 3), w('Happy', '행복한', 3), w('Heart', '심장/마음', 3),
  w('Horse', '말', 3), w('House', '집', 3), w('Knife', '칼', 3), w('Lemon', '레몬', 3),
  w('Light', '빛/가벼운', 3), w('Lunch', '점심', 3), w('Money', '돈', 3), w('Mouse', '쥐', 3),
  w('Mouth', '입', 3), w('Music', '음악', 3), w('Night', '밤', 3), w('Nurse', '간호사', 3),
  w('Onion', '양파', 3), w('Paint', '페인트', 3), w('Paper', '종이', 3), w('Party', '파티', 3),
  w('Peach', '복숭아', 3), w('Phone', '전화기', 3), w('Piano', '피아노', 3), w('Pilot', '조종사', 3),
  w('Pizza', '피자', 3), w('Plane', '비행기', 3), w('Plant', '식물', 3), w('Plate', '접시', 3),
  w('Queen', '여왕', 3), w('Quiet', '조용한', 3), w('Radio', '라디오', 3), w('River', '강', 3),
  w('Robot', '로봇', 3), w('Ruler', '자', 3), w('Seven', '칠(7)', 3), w('Sheep', '양', 3),
  w('Shirt', '셔츠', 3), w('Short', '짧은', 3), w('Skirt', '치마', 3), w('Sleep', '자다', 3),
  w('Small', '작은', 3), w('Snake', '뱀', 3), w('Spoon', '숟가락', 3), w('Stamp', '우표', 3),
  w('Store', '가게', 3), w('Storm', '폭풍', 3), w('Story', '이야기', 3), w('Sugar', '설탕', 3),
  w('Table', '탁자', 3), w('Taste', '맛보다', 3), w('Tiger', '호랑이', 3), w('Tooth', '이(치아)', 3),
  w('Touch', '만지다', 3), w('Train', '기차', 3), w('Truck', '트럭', 3), w('Uncle', '삼촌', 3),
  w('Watch', '시계/보다', 3), w('Water', '물', 3), w('Whale', '고래', 3), w('White', '흰색', 3),

  // --- LEVEL 4 (Hard / Adjectives, Jobs, Time) ---
  w('Across', '건너서', 4), w('Active', '활동적인', 4), w('Afraid', '두려운', 4), w('Always', '항상', 4),
  w('Animal', '동물', 4), w('Answer', '대답하다', 4), w('Artist', '예술가', 4), w('Basket', '바구니', 4),
  w('Before', '전에', 4), w('Behind', '뒤에', 4), w('Bottle', '병', 4), w('Bottom', '바닥', 4),
  w('Bridge', '다리(교량)', 4), w('Bright', '밝은', 4), w('Button', '단추', 4), w('Camera', '카메라', 4),
  w('Candle', '양초', 4), w('Carrot', '당근', 4), w('Castle', '성', 4), w('Cheese', '치즈', 4),
  w('Chicken', '닭', 4), w('Church', '교회', 4), w('Circle', '원', 4), w('Coffee', '커피', 4),
  w('Corner', '모퉁이', 4), w('Doctor', '의사', 4), w('Dinner', '저녁식사', 4), w('Dragon', '용', 4),
  w('Family', '가족', 4), w('Farmer', '농부', 4), w('Father', '아버지', 4), w('Finger', '손가락', 4),
  w('Finish', '끝내다', 4), w('Flower', '꽃', 4), w('Forest', '숲', 4), w('Friend', '친구', 4),
  w('Garden', '정원', 4), w('Gentle', '부드러운', 4), w('Gloves', '장갑', 4), w('Grapes', '포도', 4),
  w('Guitar', '기타', 4), w('Hammer', '망치', 4), w('Happen', '일어나다', 4), w('Health', '건강', 4),
  w('Heaven', '천국', 4), w('Hockey', '하키', 4), w('Honest', '정직한', 4), w('Hungry', '배고픈', 4),
  w('Inside', '안에', 4), w('Island', '섬', 4), w('Jacket', '재킷', 4), w('Jungle', '정글', 4),
  w('Kitten', '새끼고양이', 4), w('Ladder', '사다리', 4), w('Lesson', '수업', 4), w('Letter', '편지', 4),
  w('Listen', '듣다', 4), w('Little', '작은', 4), w('Market', '시장', 4), w('Master', '주인', 4),
  w('Middle', '중간', 4), w('Minute', '분', 4), w('Monkey', '원숭이', 4), w('Morning', '아침', 4),
  w('Mother', '어머니', 4), w('Museum', '박물관', 4), w('Narrow', '좁은', 4), w('Nature', '자연', 4),
  w('Needle', '바늘', 4), w('Number', '숫자', 4), w('Office', '사무실', 4), w('Orange', '주황색', 4),
  w('Parent', '부모', 4), w('Parrot', '앵무새', 4), w('Pencil', '연필', 4), w('People', '사람들', 4),
  w('Picnic', '소풍', 4), w('Picture', '그림/사진', 4), w('Pocket', '주머니', 4), w('Police', '경찰', 4),

  // --- LEVEL 5 (Challenge / Abstract, Science, Complex Verbs) ---
  w('Advice', '충고', 5), w('Airport', '공항', 5), w('Answer', '대답', 5), w('Appear', '나타나다', 5),
  w('Arrive', '도착하다', 5), w('Attack', '공격하다', 5), w('Autumn', '가을', 5), w('Bakery', '빵집', 5),
  w('Balloon', '풍선', 5), w('Banana', '바나나', 5), w('Basket', '바구니', 5), w('Beaver', '비버', 5),
  w('Become', '~이 되다', 5), w('Beetle', '딱정벌레', 5), w('Believe', '믿다', 5), w('Borrow', '빌리다', 5),
  w('Bottle', '병', 5), w('Branch', '나뭇가지', 5), w('Breath', '숨', 5), w('Bridge', '다리', 5),
  w('Brother', '남자형제', 5), w('Bubble', '거품', 5), w('Bucket', '양동이', 5), w('Butter', '버터', 5),
  w('Cactus', '선인장', 5), w('Camera', '카메라', 5), w('Candle', '양초', 5), w('Canvas', '캔버스', 5),
  w('Castle', '성', 5), w('Cattle', '소떼', 5), w('Center', '중심', 5), w('Change', '바꾸다', 5),
  w('Cheese', '치즈', 5), w('Cherry', '체리', 5), w('Chicken', '닭', 5), w('Church', '교회', 5),
  w('Circle', '원', 5), w('Circus', '서커스', 5), w('Clever', '영리한', 5), w('Clinic', '병원', 5),
  w('Clothes', '옷', 5), w('Coffee', '커피', 5), w('Common', '흔한', 5), w('Cotton', '면', 5),
  w('Cousin', '사촌', 5), w('Create', '창조하다', 5), w('Danger', '위험', 5), w('Decide', '결정하다', 5),
  w('Dental', '치과의', 5), w('Desert', '사막', 5), w('Design', '디자인', 5), w('Dinner', '저녁', 5),
  w('Doctor', '의사', 5), w('Dollar', '달러', 5), w('Donkey', '당나귀', 5), w('Dragon', '용', 5),
  w('Drawer', '서랍', 5), w('Dream', '꿈', 5), w('Driver', '운전사', 5), w('Eagle', '독수리', 5),
  w('Easter', '부활절', 5), w('Eleven', '십일(11)', 5), w('Energy', '에너지', 5), w('Engine', '엔진', 5),
  w('Enough', '충분한', 5), w('Eraser', '지우개', 5), w('Escape', '탈출하다', 5), w('Excited', '신난', 5),
  w('Excuse', '변명', 5), w('Expert', '전문가', 5), w('Fabric', '천', 5), w('Famous', '유명한', 5),
  w('Father', '아버지', 5), w('Faucet', '수도꼭지', 5), w('Feather', '깃털', 5), w('Fellow', '동료', 5),
  w('Female', '여성', 5), w('Fever', '열', 5), w('Field', '들판', 5), w('Figure', '수치/모습', 5),
];
